version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: '12.19.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: CI=true yarn build
          name: Run YARN build

  test:
    executor:
      name: node/default
      tag: '12.19.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: CI=true yarn lint
          name: Run YARN lint
      - run:
          command: CI=true yarn test
          name: Run YARN test

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build