version: 2.1

orbs:
  node: circleci/node@4.1.0
  cypress: cypress-io/cypress@1.26.0

jobs:
  test:
    executor:
      name: node/default
      tag: '12.19.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: CI=true yarn lint
          name: Run YARN lint
      - run:
          command: CI=true yarn test
          name: Run YARN test

workflows:
  build-and-test:
    jobs:
      - test
      - cypress/install:
          yarn: true
          build: CI=true yarn build
          requires:
            - test
      - cypress/run:
          yarn: true
          start: CI=true npx serve -s build -l 3000
          store_artifacts: true
          wait-on: 'http-get://localhost:3000'
          requires:
            - cypress/install